services:
  app:
    build: .
    container_name: payroll-vps
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www
    environment:
      APP_ENV: production
      APP_DEBUG: 'false'
      APP_KEY: base64:byBqQKXntSXp4Q38k3cj+otmI0QfVi6PzkF5mTH1g8w=
      APP_URL: http://103.77.243.209

      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: payroll
      DB_USERNAME: root
      DB_PASSWORD: casio

      CACHE_DRIVER: redis
      QUEUE_CONNECTION: rabbitmq
      SESSION_DRIVER: redis

      REDIS_HOST: redis
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest

    depends_on:
      - mysql
      - redis
      - rabbitmq

  mysql:
    image: mysql:8.0
    container_name: payroll-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: casio
      MYSQL_DATABASE: payroll
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:7.0
    container_name: payroll-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: payroll-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  mysql-data:
